name: Arctime Auto Sign

on:
  schedule:
    - cron: '45 23 * * *'  # 每天UTC 23:45 (北京时间次日7:45)
  workflow_dispatch:

jobs:
  arctime-sign:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: Asia/Shanghai
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run with debug
      env:
        ARCTIME_USERNAME: ${{ secrets.ARCTIME_USERNAME }}
        ARCTIME_PASSWORD: ${{ secrets.ARCTIME_PASSWORD }}
      run: python arctime_auto_sign.py
      
    - name: Upload debug logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-logs
        path: |
          arctime_auto_sign.py
